spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${username}
    password: ${password}
    url: ${url}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

